// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    MODELS_AGGREGATION_FETCH_QUEUE: Queue<any>;
    AK_PRODUCTS_D1: D1Database;
    PRODUCTS_AGGREGATION_KV: KVNamespace;
    API_KEY: string;
    BOT_BYPASS_KEY: string;
    ENCRYPTION_IV: string;
    ENCRYPTION_KEY: string;
}
